[package]
authors = ["LanInk <liamxin@yeah.net>"]
edition = "2018"
name = "soul"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.44"
serde_json = "^1.0.68"
wee_alloc = "^0.4.5"
ybc = "^0.2"
yew = "^0.18"

[features]
default = []
